# Generated by Django 6.0.3 on 2026-04-05 20:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre del rol, debe ser único.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Descripción del rol."),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre completo del usuario.", max_length=100
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Correo electrónico único.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "dni",
                    models.CharField(
                        help_text="Número de documento (7 u 8 dígitos).",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{7,8}$")
                        ],
                    ),
                ),
                ("birth_date", models.DateField(help_text="Fecha de nacimiento.")),
                ("activo", models.BooleanField(default=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="app.role",
                    ),
                ),
            ],
        ),
    ]
